import Config

# Configure your database
config :react_todo_list, ReactTodoList.Repo,
  username: "postgres",
  password: "Phoenix1234",
  hostname: "localhost",
  database: "react_todo_list_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# esbuild needs to be in the PATH; the env key is for the environment passed *to*
# the command, rather than the environment *running* the command, so it can't be
# added there.
System.put_env(
  "PATH",
  System.fetch_env!("PATH") <> ":" <> Path.expand("../assets/node_modules/esbuild/bin", __DIR__)
)

# Passing --watch as the second arg to the esbuild watchers did not seem to make
# it all the way to the build.js script, even though it *did* get passed to
# System.cmd("esbuild", ["build.js", "--watch"]) at line 36 in the Phoenix dep's
# watchers.exs file. So this is a workaround. ¯\_(ツ)_/¯
System.put_env("ESBUILD_WATCH", "true")

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :react_todo_list, ReactTodoListWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "MbfcLXSTfiAaIrBdICWJkWQBhhy7e5W2FJ1nY0DUXmqjD0lBV9UqYVPSgq7GonKr",
  watchers: [
    mix: [ "assets.build", cd: Path.expand("..", __DIR__) ],
    esbuild: [ "build.js", cd: Path.expand("../assets", __DIR__) ],
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :react_todo_list, ReactTodoListWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/react_todo_list_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :react_todo_list, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
